export const defaultItems = [
  {
    uid: Math.round(Math.random() * (99999999 - 10000000) + 10000000),
    title: "Carrot",
    description: "Rabbit Varient",
    favourite: false,
    category: "Grocery",
    author: "",
  },
  {
    uid: Math.round(Math.random() * (99999999 - 10000000) + 10000000),
    title: "Tomato",
    description: "Apple Tomato",
    favourite: false,
    category: "Grocery",
    author: "",
  },
  {
    uid: Math.round(Math.random() * (99999999 - 10000000) + 10000000),
    title: "Onion",
    description: "Egypt Onion",
    favourite: false,
    category: "Grocery",
    author: "",
  },
];

export const recommendedItems = [
  {
    title: "Vegetable",
    data: [
      "Asparagus",
      "Brinjal",
      "Broccoli",
      "Carrot",
      "Beans",
      "Tomato",
      "Corn",
      "Capsicum",
      "Cucumber",
      "Drumstick",
      "Spinach",
      "Cabbage",
      "Onions",
      "Cauliflower",
      "Chilli",
      "Lemon",
      "Lime",
      "Ladies Finger",
      "Bitter gourd",
      "Pumpkin",
      "Ginger",
      "Garlic",
      "Radish",
      "Zucchini",
      "Chokes",
      "Green chilli",
      "Red chilli",
      "Kidney Beans",
      "Yam",
      "Beetroot",
      "Mushroom",
      "Spring onion",
      "Snow peas",
      "Coconut",
      "Coriander",
      "Mint",
      "Rockmelon",
      "Brussels Sprouts",
      "Sprouts",
      "Basil",
    ],
  },
  {
    title: "Fruits",
    data: [
      "Apple",
      "Apricot",
      "Avocado",
      "Banana",
      "Mango",
      "Blueberry",
      "Blackberry",
      "Raspberry",
      "Strawberry",
      "Kiwi",
      "Papaya",
      "Cranberry",
      "Melon",
      "Clementine",
      "Cherries",
      "Plum",
      "Dates",
      "Gooseberry",
      "Jackfruit",
      "Lychee",
      "Mangosteen",
      "Nectarine",
      "Pomegranate",
      "Watermelon",
      "Amla",
      "Pineapple",
      "Peach",
      "Prunes",
    ],
  },
  {
    title: "Indian",
    data: [
      "Urad Dal",
      "Toor Dal",
      "Moong Dal",
      "Channa Dal",
      "Turmeric",
      "Salt",
      "Sugar",
      "Pepper",
      "Cumin seed",
      "Elachi",
      "Tamarind",
      "Masala",
      "Samosa",
      "Pickle",
      "Basmati Rice",
      "Wheat Flour",
      "Maida",
      "Flour",
      "Chips",
    ],
  },
  {
    title: "Sea Food",
    data: ["Prawns", "Squid", "Fish"],
  },
  {
    title: "Meat",
    data: ["Chicken", "Lamb", "Goat"],
  },
  {
    title: "Nuts",
    data: ["Cashews", "Almond", "Walnut", "Peanuts", "Pine nuts"],
  },
  {
    title: "Others",
    data: [
      "Banana leaf",
      "Battery",
      "Phone charger",
      "Bulb",
      "Spoon",
      "Fork",
      "Tissue paper",
      "Napkin",
      "Serviette",
      "Knife",
      "Paper",
      "Scissors",
      "Pencil",
      "Pen",
      "Eraser",
      "Sharpner",
      "Tooth paste",
      "Soap",
      "Dishwashing liquid",
      "Laundry detergent",
      "Garbage bags",
      "Oil",
      "Olive Oil",
      "Chocolate",
      "Ice cream",
    ],
  },
];
